### ISSUE TITLE
"Registry" tab sorting issues

### ISSUE THREAD

**Issue by k1l1eN** [vessenes/persona#10]
Just pointing out that you can sort by best bid and best ask inside the overall registry but there is no indicator showing what those bids or asks are under the NFT picture like on the other tab in your own collective.  It may be useful to add to the registry so people can quickly scan the floor or ceiling of the entire Persona Ecosystem.

<img width="1078" alt="image" src="https://github.com/user-attachments/assets/5b6f0934-36b5-4d39-80e5-5004f55a5528">

**Comment by vessenes** [comment]
I think for now I want to direct people to the marketplace for that, and leave the registry more narrative focused. We may add a toggle for the registry at some point; if almost everything has bids / asks, then I'll re-look at this.
