### ISSUE TITLE
Notifications Popup

### ISSUE THREAD

**Issue by k1l1eN** [vessenes/persona#12]
Just a suggestion if its easily implemented.  It would be nice to get an indicator of what actually changed on the NFT main page for that particular event notification.  Its hard to know what actually changed.  (may be too complicated a change so I get it, but if its easy enough would be useful)

<img width="239" alt="image" src="https://github.com/user-attachments/assets/c4282c50-cbdf-4821-b396-b5bc90800331">

**Comment by vessenes** [comment]
Agreed. A lot of these niceties will come in ... as they come in. I'm closing this for now, but it will get improved for sure.
