### ISSUE TITLE
Persona Re-naming issue *reported by CD in top testers

### ISSUE THREAD

**Issue by k1l1eN** [vessenes/persona#13]
CD had reported buying the Persona "Jewel" from me and wanting to rename it to an actual jewel type but it seems the re-naming function may not yet be active.  Attached is a maxxed infusion/level Persona from my collective that doesnt seem to allow renaming yet.

<img width="1086" alt="image" src="https://github.com/user-attachments/assets/3130f983-75a8-45d0-a9b5-5b5a1320e9a9">

**Comment by vessenes** [comment]
That is correct. Renaming is not implemented in the UI yet.  This is working on the smart contract side, although for v0.2 we'll want to validate that the level checks are synced up.

**Comment by vessenes** [comment]
fixed in dev
