### ISSUE TITLE
Backstory formatting characters not hidden.

### ISSUE THREAD

**Issue by k1l1eN** [vessenes/persona#15]
When you leave a backstory on a Persona,  It leaves non-invisible characters that disrupts the immersion a bit.  It begins with ".<-p>" and ends with </p then sticks your description between those markers.
 
<img width="437" alt="image" src="https://github.com/user-attachments/assets/71b956a9-2788-40c1-ba68-9b9a09df99c8">

**Comment by vessenes** [comment]
fixed in dev
