### ISSUE TITLE
Burning Error

### ISSUE THREAD

**Issue by k1l1eN** [vessenes/persona#16]
I receive an error when trying to burn a low level infusion Persona that I own.

<img width="817" alt="image" src="https://github.com/user-attachments/assets/776ca508-db1c-4e45-9219-6595c30ea94f">

**Comment by vessenes** [comment]
Yep, that was me. For now, all Hivers are safe. For now.

**Comment by vessenes** [comment]
fixed in dev, will push soon to beta
