### ISSUE TITLE
Error MSG on FAQ screen

### ISSUE THREAD

**Issue by k1l1eN** [vessenes/persona#24]
When navigating to the FAQ I get this error message that pops up but I can close it out and keep browsing

<img width="1068" alt="image" src="https://github.com/user-attachments/assets/ad452f77-99bd-43ed-8961-41be0df15ba4">

**Comment by vessenes** [comment]
This may be something that happens between server reboots.  In production we will not be using this dev HTTP server, so I'm going to (for now) imagine this will disappear at launch. If it's persistent, let me know. I can't replicate it right this second.
