### ISSUE TITLE
When acquiring Persona, the Ask values are not reset

### ISSUE THREAD

**Issue by johnmark13** [vessenes/persona#26]
![image](https://github.com/user-attachments/assets/f803bc7b-85bf-477d-a9a2-a4ed24019edd)

The 5 was the Ask that I bid against originally.

**Comment by vessenes** [comment]
Yes. This is a known bug in the NFTAuction contract; it's fixed in dev, and the beta will show this update sometime this weekend when we reset. Thank you.

**Comment by Jackalgirl** [comment]
Just noting that this is still a thing; I know you're working on it, but I've experienced this as well (persona: https://beta.personacollective.ai/persona/1370)

**Comment by vessenes** [comment]
This is now fixed in dev, will push to beta shortly. There are a variety of other bugs in the matching that have been fixed as well.
