### ISSUE TITLE
Edited backstory disappears

### ISSUE THREAD

**Issue by jessicatoon1** [vessenes/persona#27]
From Jackalgirl
"I find that if I’ve edited a backstory, when I go to edit it again, the edit field is populated with the persona’s original backstory. "

I was able to replicate this. Once you click "edit" the backstory field defaults back to the original. So if you were to want to make any edits to an already updated backstory, you would lose all of that work. -- Toon

**Comment by vessenes** [comment]
Good find, thanks.

**Comment by vessenes** [comment]
Fixed in dev, will push soon. Plus I made you some buttons.
