### ISSUE TITLE
Persona appearing in Market, though no Ask has been made and Persona not authorized for market

### ISSUE THREAD

**Issue by Jackalgirl** [vessenes/persona#35]
My lad, https://beta.personacollective.ai/persona/1038 appears in the Market.  However, I have not authorized him for the market (and don't intend to).  It is worrying to see him in the Market as if he were for sale (which he is not).  I would recommend filtering for characters who are not authorized to be listed so that the Market does not display them.

**Comment by Jackalgirl** [comment]
Discussed this in the Discord: this is apparently an option that allows for people to signal interest in a character even though the character is not for sale.  I'm of mixed feelings on this one; the fact that a character appears in the "Market" section implies that they are on the market.  While it's good that their being listed there does not mean that someone could actually buy them out from your inventory, I think that this is likely to be confusing to newcomers.  I think it would be better, in the long term, to not list characters in the "Market" unless they've been authorized to do so.  With beefier filtering options in "Others", it would be better (imo) to make it possible to search for characters you're interested in, and then place a bid on the character's profile, even though the character is not for sale.  I would recommend a warning that placing a bid will cost gas, and does not guarantee that the Sponsor of the persona is going to react to your bid.

**Comment by vessenes** [comment]
+1 on the warnings; we have a lot of documentation work to do. 

On the market side, I may make it a high level option to take personas out of the reporting on bids, but in general we want to provide an easy way for people to see what's going on in Hive City, and so your lad will show up in the market as long as there are open bids on him. You might consider getting a rich friend to make a super high bid so everyone knows how valuable he is, though.
