### ISSUE TITLE
Able to manage Persona I don't own, including send to Vats

### ISSUE THREAD

**Issue by Jackalgirl** [vessenes/persona#37]
Just sent https://beta.personacollective.ai/persona/40 to the Vats, whom I didn't own, because auctions were still ongoing.

However, I was the first person to meet the Ask, so I think the system marked the character as mine (which she wasn't, yet).  So I authorized her for transfer, then transferred her to the Vats, and it worked.

**Comment by Jackalgirl** [comment]
Just acquired a new persona, https://beta.personacollective.ai/persona/1272 -- as of this moment, the "Ask" price is showing 6 days, 23 hours to go.  The persona is listed with me as the collector; however, I'm pretty sure that because the Ask is still active, someone could come and bid more.  But as before I've got the ability to manage this persona (including sending to the Vats), like #40.

**Comment by vessenes** [comment]
I think the system did what was right here, but the UI was confusing.

A Bid that met an ask transferred the persona to you, (but the admin interface didn't update). You then authorized and sent to the vats which is fine. BTW, you don't need to authorize if you're just going to send to the vats. at any rate, again, #26 is the real issue, along with all the UI update bugs.
