### ISSUE TITLE
Journal entries for Vats conclusions in wei instead of ETH

### ISSUE THREAD

**Issue by edkeyes-apollo** [vessenes/persona#41]
For example, https://beta.personacollective.ai/persona/1651

10/21/2024, 3:24:36 PM
My infusion session ended. I now have 10000000000000000 infusion, and a new collector.

This should have been 0.01.

**Comment by vessenes** [comment]
No, we just multiply anything ed keyes does by 1e18. 

Sorry for your loss here, that might have been really exciting for a second.
