### ISSUE TITLE
Clear the Ask (automatically or manually)

### ISSUE THREAD

**Issue by Jackalgirl** [vessenes/persona#47]
I've obtained a Persona (this one: https://beta.personacollective.ai/persona/1370) and there's an expired Ask of 0.00 still associated with him. I recommend that when Asks expire, they should automatically be removed (the text should read "No Asks"), or there should be an option for the (new) Collector to manually clear/reset the Ask.

**Comment by Jackalgirl** [comment]
Note: this is of a piece of #26 and some other Ask-related issues.

**Comment by vessenes** [comment]
Dupe of #26
