### ISSUE TITLE
Character Limit in Journal Entries

### ISSUE THREAD

**Issue by Jackalgirl** [vessenes/persona#50]
There appears to be a character limit, which is fine, but the editing interface does not give you any warning that your text will be truncated.  At a minimum, please add some text that indicates what the character limit is above the Journal Entry free text field (see: https://beta.personacollective.ai/persona/605 for an example of a cut-off entry)

**Comment by vessenes** [comment]
Great catch thanks!

**Comment by vessenes** [comment]
Fixed in dev
