### ISSUE TITLE
Purchasing Level 20 does not Purify Persona

### ISSUE THREAD

**Issue by Jackalgirl** [vessenes/persona#52]
https://beta.personacollective.ai/persona/1038 -- I have purchased level 20 for him, but there is neither an option to manually purify, nor does trying to re-select the level option do anything, and he is not showing up as purified (with the white glow).  I have tried switching back and forth between regular and 4K image and that did not resolve the issue.  I'm not sure how to check blood guilt, so there's no clear way for me to check whether a) he had some and b) it's gone now.

**Comment by vessenes** [comment]
The purification system is undergoing a revamp, and will work differently -- and you're right, the leveling up does nothing right now.
