### ISSUE TITLE
"Best Ask" suggestion

### ISSUE THREAD

**Issue by k1l1eN** [vessenes/persona#9]
I would suggest if sorting by "best ask" (maybe more important for "best offer"?) it ignores NFTs with "no ask" and has a minimum of SOME ask not just all the NFTs with NO ASK at the top of the filtered list.

<img width="1072" alt="image" src="https://github.com/user-attachments/assets/a4baafde-afa3-4ac3-b055-3671f901666a">

**Comment by vessenes** [comment]
Agreed; we get this behavior from the marketplace right now, or close to it. Changing the sort to also filter silently may be confusing, I'm going to leave it as is.
